version: '3.8'

services:
  backend_app:
    container_name: backend_app
    build: .
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/sundaram
      DATABASE_USER: postgres
      DATABASE_PASSWORD: rohith
    ports:
      - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
